### ISSUE TITLE
Error when all sides are equal

### ISSUE THREAD

**Issue by ArseniyKholod** [einsflash/Project_Pusher_Mechanism#8]
This setup has an error
![image](https://github.com/user-attachments/assets/e7f90ba1-9e7d-4b02-8e45-a03876949b35)

If sides are equal, by 0 degree is uncertainity to go from -1 degree to 1 degree, because point C have to do an instant jump at this point,
![image](https://github.com/user-attachments/assets/b1147c28-337e-4468-ba91-8428022f229a)
![image](https://github.com/user-attachments/assets/a9cda070-1afd-4c3e-9142-ef94528d68e4)

So except 0 degree model finds C normally, but exactly for 0 in this case, we obtain errors in python:

```bash
Exception in Tkinter callback
Traceback (most recent call last):
  File "D:\Spyder\pkgs\tkinter\__init__.py", line 1892, in __call__
    return self.func(*args)
  File "d:\documents\übungen\project_pusher_mechanism\src\gui.py", line 262, in update_parameter_alpha
    self.refresh()
  File "d:\documents\übungen\project_pusher_mechanism\src\gui.py", line 274, in refresh
    self.display_linkage()
  File "d:\documents\übungen\project_pusher_mechanism\src\gui.py", line 182, in display_linkage
    C_x = round(A_x + (self.linkage.C[0]-self.linkage.A[0])*scale)
ValueError: cannot convert float NaN to integer
```

**Comment by ArseniyKholod** [comment]
@einsflash, do you know how to deal here with 0 degree correctly?
